package com.challenge.customers.repository;

import com.challenge.customers.entity.Customer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import(CustomerJdbcRepository.class)
class CustomerRepositoryTest {
    @Autowired JdbcTemplate jdbcTemplate;
    @Autowired CustomerJdbcRepository jdbcRepository;

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS customers");
        jdbcTemplate.execute("""
                CREATE TABLE customers (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(120) NOT NULL,
                    cpf VARCHAR(11) NOT NULL UNIQUE,
                    email VARCHAR(160) NOT NULL,
                    status VARCHAR(20) NOT NULL
                )
                """);
        jdbcTemplate.update("INSERT INTO customers(name, cpf, email, status) VALUES(?,?,?,?)",
                "Joao da Silva", "12345678901", "joao@email.com", "ACTIVE");
        jdbcTemplate.update("INSERT INTO customers(name, cpf, email, status) VALUES(?,?,?,?)",
                "Maria Souza", "98765432100", "maria@email.com", "INACTIVE");
    }

    @Test
    void shouldSearchNameUsingJdbcTemplate() {
        List<Customer> result = jdbcRepository.searchByName("joao");
        assertThat(result).hasSize(1);
        assertThat(result.get(0).getCpf()).isEqualTo("12345678901");
    }
}
